/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MembersProfileRouteImport } from './routes/members-profile'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IdCardStudioRouteImport } from './routes/id-card-studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersMemberIdRouteImport } from './routes/members.$memberId'

const MembersProfileRoute = MembersProfileRouteImport.update({
  id: '/members-profile',
  path: '/members-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdCardStudioRoute = IdCardStudioRouteImport.update({
  id: '/id-card-studio',
  path: '/id-card-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => MembersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/id-card-studio': typeof IdCardStudioRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/members-profile': typeof MembersProfileRoute
  '/members/$memberId': typeof MembersMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/id-card-studio': typeof IdCardStudioRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/members-profile': typeof MembersProfileRoute
  '/members/$memberId': typeof MembersMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/id-card-studio': typeof IdCardStudioRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/members-profile': typeof MembersProfileRoute
  '/members/$memberId': typeof MembersMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/id-card-studio'
    | '/login'
    | '/members'
    | '/members-profile'
    | '/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/id-card-studio'
    | '/login'
    | '/members'
    | '/members-profile'
    | '/members/$memberId'
  id:
    | '__root__'
    | '/'
    | '/id-card-studio'
    | '/login'
    | '/members'
    | '/members-profile'
    | '/members/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdCardStudioRoute: typeof IdCardStudioRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRouteWithChildren
  MembersProfileRoute: typeof MembersProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/members-profile': {
      id: '/members-profile'
      path: '/members-profile'
      fullPath: '/members-profile'
      preLoaderRoute: typeof MembersProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/id-card-studio': {
      id: '/id-card-studio'
      path: '/id-card-studio'
      fullPath: '/id-card-studio'
      preLoaderRoute: typeof IdCardStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof MembersRoute
    }
  }
}

interface MembersRouteChildren {
  MembersMemberIdRoute: typeof MembersMemberIdRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersMemberIdRoute: MembersMemberIdRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdCardStudioRoute: IdCardStudioRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRouteWithChildren,
  MembersProfileRoute: MembersProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
